config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :reservations

  #sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  root to: 'welcome#index'
  get 'reservations', to: 'reservations#index'
  get 'calendar'    , to: 'reservations#calendar'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate  :end_after_start

  def end_after_start
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end

  def start_time
        self.start_date
  end

  def end_time
        self.end_date
  end



  # list all scope
  scope :order_descending, -> { order(created_at: :desc) }




end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'application_reservation'

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.order_descending
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user


    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservations_path, notice: 'Reservierung erfolgreich gespeichert.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservations_path, notice: 'Reservierung erfolgreich geändert.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservierung erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  def calendar
    @reservations = Reservation.all

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:title, :start_date, :end_date, :comment)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation do|form| %>
    <%= render 'shared/error_messages' %>


      <div class="field">
        <%= form.label :Titel %>
        <%= form.text_field :title, id: :reservation_title, class: "form-control" %>
      </div>

      <div class="field">
        <%= form.label :Von %>
        <%= form.text_field :start_date, id: :reservation_start_date, class: :datepicker %>
      </div>

      <div class="field">
        <%= form.label :Bis %>
        <%= form.text_field :end_date, id: :reservation_end_date, class: :datepicker %>
      </div>

      <div class="field">
        <%= form.label :Kommentar %>
        <%= form.text_area :comment, id: :reservation_comment, :class => "materialize-textarea" %>
      </div>

      <div class="actions">
        <%= form.submit 'Speichern', :class => "waves-effect waves-light btn-large"  %>
      </div>
<% end %>

app/views/reservations/calendar.html.erb
<div class = "container">
  <h3> Kalender </h3>
  <div id="calendar"></div>
</div>

app/views/reservations/edit.html.erb
<div class = "container">
  <h3>Reservierung bearbeiten</h3>
        <%= render 'form', reservation: @reservation %>

        <%= link_to 'Anzeigen', @reservation %> |
        <%= link_to 'Zurück', reservations_path %>
  </div>

app/views/reservations/index.html.erb
<div class="center-align">
  <h3>Alle Reservierungen</h3>
    <div class="row">
      <% @reservations.each do |reservation| %>
        <% cache reservation do %>
      <div class="col s12 m6">
        <div class="card">
          <div class="card-image">
            <%= image_tag(reservation.user.avatar.url, class: "responsive-img") %>
            <span class="card-title"><%= truncate(reservation.user.username, length: 25) %></span>
            <%= link_to '<i class="material-icons">add</i>'.html_safe, reservation, :class => "btn-floating halfway-fab waves-effect waves-light red" %>
          </div>
          <div class="card-content">
            <p><%= truncate(reservation.title, length: 64) %></p>
            <p><%= reservation.start_date.strftime("%d.%m.%Y") %> -<%= reservation.end_date.strftime("%d.%m.%Y") %> </p>
          </div>
          <div class="card-action">
            <%= link_to 'Anzeigen', reservation %>
            <%= link_to 'Bearbeiten', edit_reservation_path(reservation) %>
            <%= link_to 'Löschen', reservation, method: :delete, data: { confirm: 'Bist du sicher?' } %>
          </div>
        </div>
      </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class = "container">
  <h3>Neue Reservierung für Mallorca speichern</h3>

  <%= render 'form', reservation: @reservation %>

  <%= link_to 'Zurück', reservations_path %>
</div>

app/views/reservations/show.html.erb
<div class = "container">
  <h3>Reservierung | <%= @reservation.title %> </h3>
</div>
<div class = "container">
  <ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="material-icons">face</i>Reservierung von</div>
      <div class="collapsible-body"><span><%= @reservation.user.username %></span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">short_text</i>Titel</div>
      <div class="collapsible-body"><span><%= @reservation.title %></span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">flight_land</i>Von</div>
      <div class="collapsible-body"><span><%= @reservation.start_date.strftime("%d.%m.%Y") %></span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">flight_takeoff</i>Bis</div>
      <div class="collapsible-body"><span><%= @reservation.end_date.strftime("%d.%m.%Y") %></span></div>
    </li>
    <li>
      <div class="collapsible-header"><i class="material-icons">insert_comment</i>Kommentar</div>
      <div class="collapsible-body"><span><%= @reservation.comment %></span></div>
    </li>
  </ul>
  <%= link_to 'Bearbeiten', edit_reservation_path(@reservation), class: "btn" %> |
  <%= link_to 'Zurück', reservations_path %>
</div>