config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :reservations

  #sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  root to: 'welcome#index'
  get 'reservations', to: 'reservations#index'
  get 'calendar'    , to: 'reservations#calendar'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
        <footer class="page-footer blue darken-1">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Powerd by Sepp</h5>
                <a id="something" class="btn">Aktiviere Superkraft</a>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><%= link_to "Follow me @Github", "https://github.com/dondaum", class: "grey-text text-lighten-3" %></li>
                  <li><%= link_to "Thanks @materializecss", "http://materializecss.com/", class: "grey-text text-lighten-3" %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © <%= Time.new.year %> Hardwork
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>

app/views/layouts/_header.html.erb
<nav>
  <nav class ="blue darken-1">
    <div class="nav-wrapper">
      <%= link_to "Heldenurlaub", root_path, class: "brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "Neue Reservierung", new_reservation_path %></li>
        <li><%= link_to "Reservierungen", reservations_path %></li>
        <li><%= link_to "Kalender", calendar_path %></li>
        <% if user_signed_in? %>
         <li><%= link_to "#{current_user.username}", edit_user_registration_path, class: "red lighten-1" %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to "Registrieren", new_user_registration_path %></li>
         <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to "Neue Reservierung", new_reservation_path %></li>
        <li><%= link_to "Reservierungen", reservations_path %></li>
        <li><%= link_to "Kalender", calendar_path %></li>
        <% if user_signed_in? %>
         <li><%= link_to "#{current_user.username}", edit_user_registration_path %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to "Registrieren", new_user_registration_path %></li>
         <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= javascript_tag "Materialize.toast('#{msg}', 4000, 'red rounded')" %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MallorcaPlanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  </head>

  <body>
    <%= render "layouts/header" %>
        <%= render 'layouts/messages' %>
        <%= yield %>
      <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application_reservation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MallorcaPlanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class "container" id ="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>